spring.application.name=spring-ai-playground

spring.ai.openai.api-key=${LLM_API_KEY}
spring.ai.openai.base-url=https://api.cloudflare.com/client/v4/accounts/a9f349d916d67f53cbcd59d288737d98/ai/v1
spring.ai.openai.chat.model=@cf/zai-org/glm-4.7-flash